[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
billy_bonding_curve = "71odFTZ59cG8yyBtEZrnJdBYaepzri2A12hEc16vK6WP"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/buku/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
