[toolchain]
anchor_version = "0.29.0"
solana_version = "1.18.15"

[features]
seeds = false
skip-lint = false

[programs.devnet]
bonding-curve = "898RNYePTRDQaQCdvVfZdPo82vekCJXyLfc2XsWUZVx5"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "./keys/test-kp.json"

[scripts]
test = "rm -rf programs/.bin && yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
